MS_Endpoints = {
  LOGIN: "login",
  SET_PASSWORD: "change/pass",
  FORGOT_PASSWORD: "forgot/pass",
  RESET_PASSWORD: "reset/pass",
  GET_WELCOME_API: "user/welcome",
  LOGOUT: "logout",
  PROGRAMS_LIST: "program-assign/user",
  CARD_LIST: "card/cardListing/",
  LIKE_CARDS: "card/likedCards/",
  HOSPITAL_DETAILS: "organisation/public/info/",
  PROGRAM_TRACK: "program-track/",
  PROGRAM_STAGE_TRACK: "program-track/userStage/getall",
  CARD_ACTION: "card/action/",
  CART_DATA: "card/",
  GET_ASSESSMENTS: "assessment/userAssessments",
  GET_ASSESSMENTS_DETAILS: "assessment/questionUser/",
  SAVE_USER_ASSESSMENTS: "userAssessment/",
  GET_JOURNAL: "journal/userJournal/list",
  USER: "user",
  GET_JOURNAL_QUESTIONS: "Journal/questionUser/",
  VIEW_ASSESSMENTS_DETAILS: "userAssessment/",
  SAVE_JOURNAL_QUESTIONS: "userJournal/",
  GET_JOURNAL_VIEW_QUESTIONS: "userJournal/",
  CHATBOT: "chatbot/",
  GET_TERMS_CONDITIONS_DETAILS: "help-center/termsofuse",
  GET_PRIVACY_POLICY_DETAILS: "help-center/privacypolicy",
  // GET_JOURNAL_QUESTIONS:"/userJournal/"

  GET_ALL_TRACKERS_LIST: "tracker/user",
  FETCH_ALL_TRACKERS: "tracker/user/filled/subtrack/",
  FETCH_USER_REPORTS: "tracker/report/user",
  FETCH_POINTS: "user/userPoints",
  FETCH_HELP_LIST: "help-center/help/list",
  ADD_TIME_TRACKER_API: "track/timetracker",
  USER_LAST_SEEN: "user/lastSeen",
  USER_UPADYE: "user/mobile/update",
  PROGRAM: "program/userprogram/activated",
  GET_ACTIVE_PRGRAM: "program/user/",
  GET_CURRUNT_STAGE: "chatbot/getEvent/",
};
module.exports = MS_Endpoints;
