const landmarkSize = 2;
export default {
    homeContainer: {
        flex: 1,
        // backgroundColor: 'red'
      },
      container: {
        // flex: 1,
        // paddingTop: 10,
        // backgroundColor: '#000',
        flex: 1,
        flexDirection: "column",
        backgroundColor: "black",
      },
      flipButton: {
        flex: 0.3,
        height: 40,
        marginHorizontal: 2,
        marginBottom: 10,
        marginTop: 10,
        borderRadius: 8,
        borderColor: "white",
        borderWidth: 1,
        padding: 5,
        alignItems: "center",
        justifyContent: "center",
      },
      flipText: {
        color: "white",
        fontSize: 15,
      },
      zoomText: {
        position: "absolute",
        bottom: 70,
        zIndex: 2,
        left: 2,
      },
      picButton: {
        backgroundColor: "darkseagreen",
      },
      facesContainer: {
        position: "absolute",
        bottom: 0,
        right: 0,
        left: 0,
        top: 0,
      },
      face: {
        padding: 10,
        borderWidth: 2,
        borderRadius: 2,
        position: "absolute",
        borderColor: "#FFD700",
        justifyContent: "center",
        backgroundColor: "rgba(0, 0, 0, 0.5)",
      },
      landmark: {
        width: landmarkSize,
        height: landmarkSize,
        position: "absolute",
        backgroundColor: "red",
      },
      faceText: {
        color: "#FFD700",
        fontWeight: "bold",
        textAlign: "center",
        margin: 10,
        backgroundColor: "transparent",
      },
      text: {
        padding: 10,
        borderWidth: 2,
        borderRadius: 2,
        position: "absolute",
        borderColor: "#F00",
        justifyContent: "center",
      },
      textBlock: {
        color: "#F00",
        position: "absolute",
        textAlign: "center",
        backgroundColor: "transparent",
      },
      preview: {
        flex: 1,
        justifyContent: "flex-end",
        alignItems: "center",
      },
      capture: {
        flex: 0,
        backgroundColor: "#fff",
        borderRadius: 5,
        padding: 15,
        paddingHorizontal: 20,
        alignSelf: "center",
        margin: 20,
      },
}