export const en = {
  tab: {
    home: "Home",
    resource: "Resource",
    chat: "Chat",
    help: "Help",
  },
  tab3: {
    DAILY_PLAYLIST: "Daily Playlist",
    sleep_tracker: "Sleep Tracker",
    learning: "Daily Learning",
    mood: "Mood Check In",
    activity: "Activity Tracker",
    journal: "Journal",
    video: "Video",
    doc: "Documents",
    appointment: "Appointment",
  },
  home: {
    stage: "Stage",
    temp: "Your Weight & Body Temperature",
    sleep: "How did you sleep last night?",
    activity: "What activities have you done?",
    mood: "What is your mood today?",
    sleepCU002: "Baby Sleep Tracker",
    activityCU002: "Baby Diaper Tracker",
    moodCU002: "Baby Mood Tracker",
    hi: "Hi",
    week: "Week",
    learning_heading: "Today's Daily Learning",
    todays_learning: "Today's Learning",
    learning_desc:
      "Learn something new today and take it with you whenever you go",
    points: "Points",
    day: "Day",
    month: "Month",
    networkAlert: "Please try connecting later as API is currently down",
    complete_learning:
      "Great job! You’ve completed your daily learning for the day. Come back again tomorrow to complete your next lesson. You can visit My Learnings to review past lessons.",
  },
  resource: {
    resources: "Resources",
    assessment: "Assessments",
    care_team: "Care Team",
    my_learning: "My Learnings",
    report: "Report",
    schedule: "Schedule",
    concern: "Care concerns",
    proceed: "Proceed",
    ByDate: "By Date",
    Liked: "Liked",
    Week: "Week",
    SelectWeek: "Select Week",
    suggested: "Suggested",
  },
  login: {
    username: "Username",
    usernameHint: "Enter your username",
    button: "Login",
    //password: 'Password',
    //passwordHint: 'Enter your password',
    invalidCredentials: "Invalid Username/Password",
    title: "Log in",
    remember: "Remember Me",
    forgot_pass: "Forgot Email/Password?",
    email_label: "Email",
    EMAIL_ERROR: "Email address is invalid!",
    passowrd_require: "Password is required",
    cp_require: "Confirm password is required",
    ack: "Please acknowledge you are 18 or older and accept",
    terms: "Terms of Use",
    privacy: "Privacy Policy",
    and: "and",
    pass_not_same: "New password and confirm password does't match",
    welcome_continue: "Let's Continue!",
    welcome_title: "Welcome to",
    forgotPassword: "Forgot Password"
  },
  profile: {
    header: "Profile",
    Account: "Account",
    Notification: "Notification",
    Privacy: "Privacy & Security",
    Language: "Language",
    info: "App Info",
    logout: "Logout",
    english: "English",
    spanish: "Spanish",
    save: "Save",
    success: "Success",
    lang_success: "App language changed successfully.",
    logoutText: "Are you sure you want to logout?",
    yes: "Yes",
    no: "No",
    German: "German",
    hindi: "Hindi",
  },
  Account: {
    provider: "Provider Details",
    // change_password: 'Change Password',
    personalization: "Personalization",
    // currunt_password: 'Current Password',
    //new_password: 'New Password',
    //confirm_password: 'Confirm New Password',
    personalization: "Personalization",
    providerName: "Provider Name",
    providerId: "Provider ID",
    hospitalName: "Hospital Name",
    hospitalId: "Hospital ID",
    search: "Search",
    //set_password: 'Set Password',
  },
  SleepTracker: {
    select_date: "Select Date",
    sleep_hours: "How many hours did you sleep today including naps?",
    sleep_hoursCU002: "How many hours did your baby sleep including naps ?",
    sleep_scale: "How well did you sleep on a scale of 1-10?",
    energetic_scale: "How energetic do you feel on a scale of 1-10?",
    sleep_scaleCU002:
      "How energetic do you think your baby feels on a scale of 1 - 10? ",
    energetic_scaleCU002: "How do you think your baby feels right now?",
    history: "Last 7 days history",
    Sleep_hours_day: "Daily Sleep Tracker: Hours/Day",
    Sleep_hours_day_baby: "Weekly Baby Sleep Tracker Report",
    Sleep_Quality: "Weekly Sleep Quality Report",
    Sleep_Quality_baby: "Weekly Baby Sleep Quality Report",
    Energy_weekly: "Weekly Energy Report",
    Energy_weekly_baby: "Weekly Baby Energy Report",
    add_tracking: "ADD TRACKING",
    SleepTracker: "Sleep Tracker",
    baby_sleep_heading: "Baby Sleep Tracker",
  },
  activity: {
    other_activity_title: "Search Pleasant Activity",
    search_place_holder: "Search activity by name (ex: Sport)",
    activity_title: "What have you been up to?",
    activity_titleCU002: "How many diapers have you changed today?",
    save_txt: "Save",
    Add: "Add",
    Activity: "Activity",
    alertText: "Please select Activities",
    ActivityTracker: "Activity Tracker",
    ActivityTrackerCU002: "Diaper Tracker",
    AddNewActivity: "Add New Activity",
    Activities: "Pleasant Activities",
    DailyActivities: "Daily Activities",
  },
  mood: {
    title: "How are you feeling right now?",
    titleCU002: "How is your baby feeling right now?",
    mood_validation: "Please select mood",
    MoodCheckIn: "Mood Check-In",
    days: "In the past 7 days, you were:",
    next: "NEXT",
    finish: "FINISH",
    daysCU002: "In the past 7 days, your baby was:",
  },
  points: {
    No_data_found: "No data found",
    TotalPoints: "Total Points",
    Daily: "Daily",
    Weekly: "Weekly",
    Monthly: "Monthly",
  },
  assessment: {
    SelectAsessmentType: "Select Assessment Type",
    No_assessments: "No assessments are available",
  },
  journal: {
    title: "Select Journal type",
    default: "No journal are available",
    Type_here: "Type here for anything else you want us to know",
    Past_entries: "Past entries",
    Read_more: "Read more",
    No_options: "No options are available",
    EditJournal: "Edit Journal",
    NoQuestions: "No questions are available",
  },
  reports: {
    Reports: "Reports",
    ReportDate: "Report Date",
    dailySleepTracker: "Daily Sleep Tracker",
    hoursDay: "hours/ day",
    AverageDailyMoodReport: "Average Daily Mood Report",
    WeeklyMoodReport: "Weekly Mood Report",
    WeeklyMoodReport_baby: "Weekly Baby Mood Report",
    NoRecordforthisweek: "No Record for this week",
    DailyActivityReport: "Daily Activity Report: Number of Activities",
    WeeklyActivityReport: "Weekly Activity Report",
    YourtotalPointsfortheweek: "Your total Points for the week",
    baby_sleep: "Weekly Baby Sleep Tracker Report",
    baby_mood: "Average Baby Mood Report",
    diaper_report: "Weekly Baby Diaper Change Report",
    weekly_diaper: "Weekly Diaper Activity Report",
  },
  notification: {
    push_notification: "Push Notification",
    email_notification: "Email Notification",
    sms_notification: "SMS Notification",
  },
  appInfo: {
    version: "Version",
    build: "Build",
    lastUpdate: "Last Update",
    offeredby: "Offered by",
    releasedOn: "Released on",
  },
  camera: {
    initializing: "Initializing Camera.... Please Wait",
    uploadProfile: "Upload Profile",
    retake: "Retake",
    setProfilePhoto: "Set Profile Photo",
    cancel: "Cancel",
    enableSetting: "Enable camera permission from Settings.",
    unablePermission: "Unable to complete task without camera permission.",
    clickHere: "Click here",
    to: "to",
  },
  careTeam: {
    MyCareTeam: "My Care Team",
    no_text: "No care team member is available",
    Contacts: "Contacts",
  },
  careConcerns: {
    General: "General",
    Suggested: "Suggested",
    Upcoming: "Upcoming",
  },
  Schedule: {
    Appointment: "Appointment",
    BOOKED: "Booked",
    UPCOMING: "Upcoming",
    COMPLETED: "Completed",
    MISSED: "Missed",
    SymptomsFreeDay2: "Symptoms Free day (2 days)",
    Mildcanfunction12: "Mild can function (12 days)",
    Moderateslowed3: "Moderate slowed (3 Days)",
    EmptyDays8: "Empty Days (8 DAYS)",
    Todaysappointment: "Today's appointment",
    Time: "Time :",
    CareTaker: "CareTaker :",
    Wegotthefeedback: "We got the feedback.",
    Gotomyplaylist: "Go to my playlist",
    text:
      "We have got your feedback John! We will update your daily playlist according to your feedback.Have a good day.",
    NO_APPOINTMENTS: "No appointments",
  },
  CoustomAlert: {
    msg:
      "Congrats! You have completed today's Daily Learning. Tomorrow's content will be available at midnight.",
    ok: "OK",
    server_is_not_reachable:
      "The server is not reachable right now, sorry for inconvenience.",
  },
  chat: {
    Document: "Document",
    Gallery: "Gallery",
    Note:
      "Note: Please expect 24-48 hours delay in response. If you have an emergency please call 911 or go to nearest ER.",
    Close: "Close",
    noChat: "No chat is available",
    ChatWithStella: "Chat with Stella",
  },
  chatBot: {
    toptitle: "Setting Up Chat",
    title: "Get to know you better",
    talk: "Press here to talk to ROBO.",
    minutes: "minutes",
    songs: "songs",
    AnArticle: "An Article",
    FavoriteMusic: "Favorite Music",
  },
  cards: {
    reflect: "Reflect",
    comment: "Comment",
    yes: "YES",
    no: "NO",
    submit: "Submit",
    previous: "Previous",
    step_thanks:
      "Thanks for completing the 3-step activity. Swipe left for the next card.",
    swipe: "Swipe",
    back: "Back",
    validation_perform: "Please perform your exercise.",
    reflect_title: "Reflect on today's quote.",
    quote_mean: "This quote means...",
    no_like_card: "You haven't liked any card yet.",
    no_suggested: "No suggested cards found.",
    all_read: "All cards seen.",
    liked_cards: "Liked Cards",
    suggested_cards: "Suggested Cards",
    program: "Programs",
    CUSTOM_MSG1:
      "After the birth of your new born, you consider that changes have occurred in ",
    CUSTOM_MSG2: " areas of your life and that, in ",
    CUSTOM_MSG3:
      " of these areas, these changes were different from what you initially thought. Many mothers describe differences between what they imagined their life would be like during pregnancy, and the reality of the changes after the baby arrives! In fact, it is normal for the experience of taking care of our baby to be different from what we imagined or expected, even when it is not our first child. Every pregnancy and every baby are different and unique!",
    CUSTOM_MSG4: "You identified",
    CUSTOM_MSG5:
      "topics where your experiences and your partner's experiences may have been different or, at least, where you do not know if your experiences were similar or not.  It is possible that both your different experiences influence your idea of what it is like to 'be a good mother' and 'to be a good father'.This means that in addition to creating an idea of you as a mother(the mother you want to be) you have also created an idea of your partner as a father/ mother you want them to be, and your partner did the same.These ideas seem “natural” and “the absolute truth” because that is the reality you have always known - but your partner has lived another reality and, therefore, their ideas may be different",
  },
  validation: {
    select_activity: "Please select activity",
    SECURITY_ALERT: "Security Alert",
    SECURITY_ALERT_TEXT:
      "This device appears to be jailbroken. There are inherent risk with jailbrocken device. Continue at your own risk.",
    SECURITY_ALERT_TEXT_ANDROID:
      "This device appears to be root. There are inherent risk with rooted device. Continue at your own risk.",
    //  PASSWORD_ERROR:
    //    'Minimum 8 character length, atleast 1 special character and 1 digit',
    PASSWORD_ERROR:
      "Minimum 8 alphanumeric characters with atleast 1 uppercase letter, 1 number and 1 special character (!,@,#,$,%,^,&,*)",
    Error: "Error",
    EmptyPersonalization: "Please select keywords",
  },
  APP_INFO: {
    CurioDigital: "Curio Digital",
    momentLanguage: "en",
  },
  JOURNAL_POPUP: "Your Journal is saved successfully.",
  AFTER_BIRTH:
    "After the birth of your new born, you consider that changes have occurred in ${X1} areas of your life and that, in ${X2} of these areas, these changes were different from what you initially thought.​  Many mothers describe differences between what they imagined their life would be like during pregnancy, and the reality of the changes after the baby arrives! In fact, it is normal for the experience of taking care of our baby to be different from what we imagined or expected, even when it is not our first child.​Every pregnancy and every baby are different and unique!",
  PERFORM_EXERCISE: "Please perform exercise.",
  PLEASE_FILL_SLEEP: "Please fill Sleep Hours",
  MISSED_CONTENT_ALERT:
    "You have missed the content for previous day. Please read that first.",
  PLEASANT_ACTIVITY: "What pleasant activities have you done",
  APPOINTMENT_NOTES:
    "Note: You can request for appointment from this page. You can select 6 preferred days and the care team will confirm the available appointment based on doctor's schedule.",
  SELECT_SESSION: "Select session",
  SELECT_AVAILABLE_SLOT: "Select available slot",
  APPOINTMENT_SUCCESS: "Your appointment request has been added successfully",
  SELECT_UPTO_3_OPTIONS: "Select upto 3 options.",
  WRITE_MSG: "Write a message",
  RESPONSE_ERR: {
    "1": "Internal Server Error.",
    "2": "Session Expired. Please login again!",
    "7": "Incorrect Password",
    "8": "User does not exist",
    "406": "Validation error",
    "500": "Internal Server Error.",
    "17": "Account temporarily blocked for 30 Minutes",
    "10": "Old password is incorrect",
    "16": "User is deleted",
    "404": "The server is not reachable right now, sorry for inconvenience.",
  },
  Content_not_available: "Content not available",
};
