export const es = {
  tab: {
    home: "Hogar",
    resource: "Recurso",
    chat: "Charlar",
    help: "Ayudar",
  },
  tab3: {
    DAILY_PLAYLIST: "Lista de reproducción diaria",
    sleep_tracker: "Rastreador de sueño",
    learning: "Aprendizaje diario",
    mood: "Registro de estado de ánimo",
    activity: "Rastreador de actividad",
    journal: "diario",
    video: "Video",
    doc: "Documentos",
    appointment: "Cita",
  },
  home: {
    stage: "la etapa",
    temp: "Su peso y temperatura corporal",
    sleep: "¿Como dormiste anoche?",
    activity: "¿Qué actividades has realizado?",
    mood: "¿Cuál es tu estado de ánimo hoy?",
    sleepCU002: "Seguimiento del sueño del bebé",
    activityCU002: "Rastreador de pañales para bebés",
    moodCU002: "Seguimiento del estado de ánimo del bebé",
    hi: "Hola",
    week: "Semana",
    learning_heading: "Aprendizaje diario de hoy",
    todays_learning: "El aprendizaje de hoy",
    learning_desc: "Aprenda algo nuevo hoy y llévelo con usted cuando vaya",
    points: "Puntos",
    day: "Día",
    month: "Mes",
    networkAlert:
      "Intente conectarse más tarde ya que la API está actualmente inactiva",
    complete_learning:
      "¡Gran trabajo! Has completado tu aprendizaje diario del día. Vuelve mañana para completar tu próxima lección. Puede visitar Mis aprendizajes para revisar las lecciones anteriores.",
  },
  resource: {
    resources: "Recursos",
    assessment: "Evaluaciones",
    care_team: "Equipo de cuidado",
    my_learning: "Mis aprendizajes",
    report: "Reporte",
    schedule: "Calendario",
    concern: "Preocupaciones de cuidado",
    proceed: "Continuar",
    ByDate: "Por fecha",
    Liked: "Apreciada",
    Week: "Semana",
    SelectWeek: "Seleccionar semana",
    suggested: "Sugerido",
  },
  login: {
    username: "Username",
    usernameHint: "Enter your username",
    button: "Login",
    // password: 'Password',
    //passwordHint: 'Enter your password',
    invalidCredentials: "Invalid Username/Password",
    title: "Iniciar sesión",
    remember: "Recordarme",
    forgot_pass: "Olvidé mi correo electrónico/contraseña?",
    email_label: "Correo electrónico",
    EMAIL_ERROR: "¡Dirección de correo electrónico es inválida!",
    passowrd_require: "Se requiere contraseña",
    cp_require: "Se requiere confirmar contraseña",
    ack: "Reconozca que tiene 18 años o más y acepte",
    terms: "Términos de uso",
    privacy: "Política de privacidad",
    and: "Y",
    pass_not_same:
      "La contraseña nueva y la contraseña confirmada no coinciden",
    welcome_continue: "¡Continuemos!",
    welcome_title: "Bienvenido a",
  },
  profile: {
    header: "Perfil",
    Account: "Cuenta",
    Notification: "Notificación",
    Privacy: "Privacidad y seguridad",
    Language: "Idioma",
    info: "Informacion de la applicacion",
    logout: "Cerrar sesión",
    english: "Inglesa",
    spanish: "Española",
    save: "Ahorrar",
    success: "Éxito",
    lang_success: "El idioma de la aplicación cambió correctamente.",
    logoutText: "¿Estás segura de que quieres cerrar sesión?",
    yes: "sí",
    no: "No",
    German: "Alemán",
    hindi: "Hindi",
  },
  Account: {
    provider: "Detalles del proveedor",
    //change_password: 'Cambiar la contraseña',
    personalization: "Personalización",
    //currunt_password: 'Contraseña actual',
    //new_password: 'Nueva contraseña',
    // confirm_password: 'Confirmar nueva contraseña',
    personalization: "Personalización",
    providerName: "Nombre del proveedor",
    providerId: "ID de proveedor",
    hospitalName: "Nombre del hospital",
    hospitalId: "Identificación del hospital",
    search: "Buscar",
    //set_password: "Configurar la clave"
  },
  SleepTracker: {
    select_date: "Seleccione fecha",
    sleep_hours: "¿Cuántas horas dormiste hoy, incluidas las siestas?",
    sleep_hoursCU002: "¿Cuántas horas durmió su bebé, incluidas las siestas?",
    sleep_scale: "¿Qué tan bien dormiste en una escala del 1 al 10?",
    energetic_scale: "¿Qué tan enérgico te sientes en una escala del 1 al 10?",
    sleep_scaleCU002:
      "Wie energiegeladen, glauben Sie, fühlt sich Ihr Baby auf einer Skala von 1 - 10 an?",
    energetic_scaleCU002: "¿Cómo crees que se siente tu bebé en este momento?",
    history: "Historial de los últimos 7 días",
    Sleep_hours_day: "Rastreador diario de sueño: horas / día",

    Sleep_hours_day_baby: "Informe semanal del seguimiento del sueño del bebé",
    Sleep_Quality: "Informe semanal de calidad del sueño",
    Sleep_Quality_baby: "Informe semanal de la calidad del sueño del bebé",
    Energy_weekly: "Informe energético semanal",
    Energy_weekly_baby: "Informe semanal de energía del bebé",
    add_tracking: "AÑADIR SEGUIMIENTO",
    SleepTracker: "Rastreador de sueño",
    baby_sleep_heading: "Seguimiento del sueño del bebé",
  },
  activity: {
    other_activity_title: "Buscar actividad agradable",
    search_place_holder: "Buscar actividad por nombre (p. Ej., Deporte)",
    activity_title: "¿Qué has estado haciendo?",
    activity_titleCU002: "¿Cuántos pañales has cambiado hoy?",
    save_txt: "Ahorrar",
    Add: "Agregar",
    Activity: "Actividad",
    alertText: "Por favor seleccione Actividades",
    ActivityTracker: "Rastreador de actividad",
    ActivityTrackerCU002: "Rastreador de pañales",
    AddNewActivity: "Agregar nueva actividad",
    Activities: "Actividades agradables",
    DailyActivities: "Actividades diarias",
  },
  mood: {
    title: "¿Cómo te sientes ahora?",
    mood_validation: "Seleccione el estado de ánimo",
    MoodCheckIn: "Registro de estado de ánimo",
    days: "En los últimos 7 días, estuvo:",
    next: "SIGUIENTE",
    finish: "TERMINAR",
    daysCU002: "En los últimos 7 días, su bebé fue:",
  },
  points: {
    No_data_found: "¡Datos no encontrados!",
    TotalPoints: "Puntos totales",
    Daily: "Diaria",
    Weekly: "Semanalmente",
    Monthly: "Mensual",
  },
  assessment: {
    SelectAsessmentType: "Seleccione el tipo de evaluación",
    No_assessments: "No hay evaluaciones disponibles",
  },
  journal: {
    title: "Seleccione el tipo de diario",
    default: "No hay revistas disponibles",
    Type_here: "Escriba aquí para cualquier otra cosa que desee que sepamos",
    Past_entries: "Entradas pasadas",
    Read_more: "Lee mas",
    No_options: "No hay opciones disponibles",
    EditJournal: "Editar diario",
    NoQuestions: "No hay preguntas disponibles",
  },
  reports: {
    Reports: "Informes",
    ReportDate: "Fecha del informe",
    dailySleepTracker: "Rastreador diario del sueño",
    hoursDay: "horas / día",
    AverageDailyMoodReport: "Informe de estado de ánimo diario promedio",
    WeeklyMoodReport: "Informe de estado de ánimo semanal",
    WeeklyMoodReport_baby: "Informe semanal del estado de ánimo del bebé",
    NoRecordforthisweek: "Sin registro para esta semana",
    DailyActivityReport: "Informe de actividad diaria: número de actividades",
    WeeklyActivityReport: "Informe de actividad semanal",
    YourtotalPointsfortheweek: "Tus puntos totales de la semana",
    baby_sleep: "Informe semanal del seguimiento del sueño del bebé",
    baby_mood: "Informe de estado de ánimo promedio del bebé",
    diaper_report: "Informe semanal de cambio de pañales para bebés",
    weekly_diaper: "Informe semanal de actividad de pañales",
  },
  notification: {
    push_notification: "Notificación de inserción",
    email_notification: "Notificación de correo electrónico",
    sms_notification: "Notificación por SMS",
  },
  appInfo: {
    version: "Versión",
    build: "Construir",
    lastUpdate: "Última actualización",
    offeredby: "Ofrecido por",
    releasedOn: "Publicado el",
  },
  camera: {
    initializing: "Inicializando la cámara ... Espere",
    uploadProfile: "Subir perfil",
    retake: "Volver a tomar",
    setProfilePhoto: "Establecer foto de perfil",
    cancel: "Cancelar",
    enableSetting: "Habilite el permiso de la cámara desde Configuración.",
    unablePermission:
      "No se puede completar la tarea sin el permiso de la cámara.",
    clickHere: "haga clic aquí",
    to: "para",
  },
  careTeam: {
    MyCareTeam: "Mi equipo de cuidado",
    no_text: "Ningún miembro del equipo de atención está disponible",
    Contacts: "Contactos",
  },
  careConcerns: {
    General: "General",
    Suggested: "Sugerida",
    Upcoming: "Próxima",
  },
  Schedule: {
    Appointment: "Cita",
    BOOKED: "Reservada",
    UPCOMING: "Próxima",
    COMPLETED: "Terminada",
    MISSED: "Omitido",
    SymptomsFreeDay2: "Síntomas Día libre (2 días)",
    Mildcanfunction12: "Puede funcionar leve (12 días)",
    Moderateslowed3: "Moderado ralentizado (3 días)",
    EmptyDays8: "Días vacíos (8 DÍAS)",
    Todaysappointment: "'La cita de hoy",
    Time: "Tiempo :",
    CareTaker: "CareTaker :",
    Wegotthefeedback: "Recibimos la retroalimentación.",
    Gotomyplaylist: "Ir a mi lista de reproducción",
    text:
      "¡Tenemos tus comentarios, John! Actualizaremos su lista de reproducción diaria de acuerdo con sus comentarios. Que tenga un buen día.",
    NO_APPOINTMENTS: "sin citas",
  },
  CoustomAlert: {
    msg:
      "¡Felicitaciones! Ha completado el aprendizaje diario de hoy. El contenido de mañana estará disponible a la medianoche..",
    ok: "OK",
    server_is_not_reachable:
      "The server is not reachable right now, sorry for inconvenience.",
  },
  chat: {
    Document: "Documento",
    Gallery: "Galería",
    Note:
      "Nota: espere un retraso de 24 a 48 horas en la respuesta. Si tiene una emergencia, llame al 911 o vaya a la sala de emergencias más cercana.",
    Close: "Cerca",
    noChat: "No hay chat disponible",
    ChatWithStella: "Chatea con Stella",
  },
  chatBot: {
    toptitle: "Configurar el chat",
    title: "Llegar a conocerte mejor",
    talk: "Pulsa aquí para hablar con ROBO.",
    minutes: "minutos",
    songs: "canciones",
    AnArticle: "Un artículo",
    FavoriteMusic: "Música favorita",
  },
  cards: {
    reflect: "Reflejar",
    comment: "Comentario",
    yes: "SÍ",
    no: "NO",
    submit: "Entregar",
    previous: "Previa",
    step_thanks:
      "Gracias por completar la actividad de 3 pasos.Desliza el dedo hacia la izquierda para ver la siguiente tarjeta.",
    swipe: "Deslizar",
    back: "atrás",
    validation_perform: "Por favor realiza tu ejercicio.",
    reflect_title: "Reflexiona sobre la cita de hoy.",
    quote_mean: "Esta cita significa...",
    no_like_card: "Todavía no le ha gustado ninguna tarjeta.",
    no_suggested: "No se encontraron tarjetas sugeridas.",
    all_read: "Todas las cartas vistas..",
    liked_cards: "Tarjetas que gustan",
    suggested_cards: "Tarjeta sugerido",
    program: "Programas",
    CUSTOM_MSG1:
      "Después del nacimiento de su recién nacido, considera que se han producido cambios en ",
    CUSTOM_MSG2: " áreas de tu vida y que, en ",
    CUSTOM_MSG3:
      " de estas áreas, estos cambios fueron diferentes de lo que pensabas inicialmente. ¡Muchas madres describen las diferencias entre lo que imaginaban que sería su vida durante el embarazo y la realidad de los cambios después de la llegada del bebé! De hecho, es normal que la experiencia de cuidar a nuestro bebé sea diferente de lo que imaginábamos o esperábamos, incluso cuando no es nuestro primer hijo. ¡Cada embarazo y cada bebé son diferentes y únicos!",
    CUSTOM_MSG4: "te identificaste",
    CUSTOM_MSG5:
      "temas donde sus experiencias y las de su pareja pueden haber sido diferentes o, al menos, donde no sabe si sus experiencias fueron similares o no. Es posible que sus diferentes experiencias influyan en su idea de lo que es 'ser una buena madre' y 'ser un buen padre'. Esto significa que además de crear una idea de usted como madre (la madre que quieres ser) también has creado una idea de tu pareja como padre/madre que quieres que sea, y tu pareja hizo lo mismo. Estas ideas parecen “naturales” y “la verdad absoluta” porque esa es la realidad que tienes siempre lo ha sabido - pero su pareja ha vivido otra realidad y, por lo tanto, sus ideas pueden ser diferentes",
  },
  validation: {
    select_activity: "Por favor seleccione actividad",
    SECURITY_ALERT: "Alerta de seguridad",
    SECURITY_ALERT_TEXT_ANDROID:
      "Este dispositivo parece ser root. Hay un riesgo inherente con el dispositivo raíz. La aplicación es incompatible con su dispositivo",
    SECURITY_ALERT_TEXT:
      "Este dispositivo parece tener jailbreak. Hay un riesgo inherente con el dispositivo con jailbrock. La aplicación es incompatible con su dispositivo",
    PASSWORD_ERROR:
      "Longitud mínima de 8 caracteres, al menos 1 carácter especial y 1 dígito",
    Error: "Error",
    EmptyPersonalization: "Seleccione palabras clave",
  },
  APP_INFO: {
    CurioDigital: "curiosidades digitales",
    momentLanguage: "es",
  },
  JOURNAL_POPUP: "Su diario se guardó con éxito.",
  AFTER_BIRTH:
    "Después del nacimiento de su recién nacido, considera que se han producido cambios en ${X1} áreas de su vida y que, en ${X2} de estas áreas, estos cambios fueron diferentes de lo que pensó inicialmente.​ Muchas madres describen diferencias entre lo que imaginaban que sería su vida durante el embarazo y la realidad de los cambios después de la llegada del bebé. De hecho, es normal que la experiencia de cuidar a nuestro bebé sea diferente a lo que imaginábamos o esperábamos, incluso cuando no es nuestro primer hijo. ¡Cada embarazo y cada bebé son diferentes y únicos!",
  PERFORM_EXERCISE: "Por favor, realice el ejercicio.",
  PLEASE_FILL_SLEEP: "Por favor complete Horas de sueño",
  MISSED_CONTENT_ALERT:
    "Te has perdido el contenido del día anterior. Por favor, lea eso primero.",
  PLEASANT_ACTIVITY: "¿Qué actividades agradables has hecho?",
  APPOINTMENT_NOTES:
    "Nota: Puede solicitar cita previa desde esta página. Puede seleccionar 6 días preferidos y el equipo de atención confirmará la cita disponible según el horario del médico.",
  SELECT_SESSION: "Seleccionar sesión",
  SELECT_AVAILABLE_SLOT: "Seleccione la ranura disponible",
  APPOINTMENT_SUCCESS: "Su solicitud de cita ha sido añadida con éxito",
  SELECT_UPTO_3_OPTIONS: "Seleccione hasta 3 opciones.",
  WRITE_MSG: "Escribe un mensaje",
  RESPONSE_ERR: {
    "1": "Error de servidor interno.",
    "2": "Sesión expirada. ¡Inicia sesión de nuevo!",
    "7": "Contraseña incorrecta",
    "8": "El usuario no existe",
    "406": "Error de validacion",
    "500": "Error de servidor interno.",
    "10": "Antigua contraseña es incorrecta",
    "16": "User is deleted",
    "404":
      "El servidor no está disponible en este momento, disculpe las molestias.",
  },
};
